
OPENAI_API_TYPE="OPENAI_API_TYPE"
OPENAI_DEPLOYMENT_NAME="OPENAI_DEPLOYMENT_NAME"
OPENAI_MODEL="OPENAI_MODEL"
OPENAI_API_VERSION="OPENAI_API_VERSION"
AZURE_OPENAI_ENDPOINT="AZURE_OPENAI_ENDPOINT"
OPENAI_API_KEY="OPENAI_API_KEY"

# error
ERROR_OK = 0
ERROR_UNKNOW = 5000
ERROR_MILVUS_UNKNOWN = 5101
ERROR_MILVUS_CONNECT_FAILED = 5102

# error string
ERRSTR_MILVUS_CONNECT_FAILED = "Failed to connect Milvus database"

# arguments
ARGS_CONNECTION_ARGS = "connectionArgs"
ARGS_RESULT_NUM = "resultNum"
ARGS_CHUNK_SIZE = "chunkSize"
ARGS_OVERLAP_SIZE = "overlapSize"
ARGS_SPLIT_BY_CHAR = "splitByChar"
ARGS_DOCIDS_WORKSPACE = "docIdsWorkspace"
ARGS_USE_REFLEXION = "useReflexion"

