
OPENAI_API_TYPE="OPENAI_API_TYPE"
OPENAI_DEPLOYMENT_NAME="OPENAI_DEPLOYMENT_NAME"
OPENAI_MODEL="OPENAI_MODEL"
OPENAI_API_VERSION="OPENAI_API_VERSION"
AZURE_OPENAI_ENDPOINT="AZURE_OPENAI_ENDPOINT"
AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT_NAME="AZURE_OPENAZURE_OPENAI_EMBEDDINGS_DEPLOYMENT_NAMEAI_EMBEDDINGS_MODEL"
AZURE_OPENAI_EMBEDDINGS_MODEL="AZURE_OPENAI_EMBEDDINGS_MODEL"
OPENAI_API_KEY="OPENAI_API_KEY"
TOKEN_DAILY_LIMITATION="TOKEN_DAILY_LIMITATION"

# error
ERROR_OK = 0
ERROR_UNKNOWN = 5100
ERROR_MILVUS_UNKNOWN = 5101
ERROR_MILVUS_CONNECT_FAILED = 5102
ERROR_EXCEEDS_TOKEN_LIMIT = 5103

# error string
ERRSTR_MILVUS_CONNECT_FAILED = "Failed to connect Milvus database"

# arguments
ARGS_CONNECTION_ARGS = "connectionArgs"
ARGS_RESULT_NUM = "resultNum"
ARGS_CHUNK_SIZE = "chunkSize"
ARGS_OVERLAP_SIZE = "overlapSize"
ARGS_SPLIT_BY_CHAR = "splitByChar"
ARGS_DOCIDS_WORKSPACE = "docIdsWorkspace"
ARGS_USE_REFLEXION = "useReflexion"

DATA_DIR = "DATA_DIR"
AZURE_COMMUNITY = "Azure Gpt Community"
GPT_COMMUNITY = "Gpt Community"


